version: '3.8'

services:
  todo-app:
    build:
      context: ./app
    depends_on:
      - db-alunos-ciencia
      - db-alunos-super
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
      - "35729:35729"

  db-alunos-ciencia:
    build:
      context: ./db-ciencia
      dockerfile: Dockerfile.db-ciencia
    volumes: 
      - database:/data/db
    ports:
      - "27017:27017"

  db-alunos-super:
    build:
      context: ./db-super
      dockerfile: Dockerfile.db-super
    volumes: 
      - database2:/data/db
    ports:
      - "27018:27017"  # Escolha uma porta diferente para evitar conflito

volumes:
  database:
  database2:
